app/urls.py
from django.contrib import admin
from django.urls import include, path




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('parser/', include('parser.urls', namespace='parser')),
    path('analytics/', include('analytics.urls', namespace='analytics')),
    path('analysis/', include('analysis.urls', namespace='analysis')),
]

goods/urls.py
from django.urls import path

from goods import views

app_name = "goods"

urlpatterns = [
    path('', views.catalog, name='index'),
]

goods/models.py
from django.db import models

class Flats(models.Model):
    flat_id = models.AutoField(primary_key=True)
    date = models.CharField(max_length=20)
    price = models.IntegerField()
    apartment_size = models.FloatField()
    rooms = models.IntegerField()
    floor = models.IntegerField(null=True, blank=True)
    floor_max = models.IntegerField(null=True, blank=True)
    place = models.CharField(max_length=200)
    link = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.place} - {self.price} $"

    class Meta:
        db_table = "flats2"  # Соответствие имени таблицы в базе данных

goods/views.py
from django.shortcuts import render
from django.template import context
from django.utils import timezone
from datetime import timedelta

from .models import Flats


def catalog(request):
    # Начальные параметры фильтрации
    apartments = Flats.objects.all()

    # Получение параметров фильтрации
    rooms = request.GET.get("rooms")
    min_size = request.GET.get("min_size")
    max_size = request.GET.get("max_size")
    order_by = request.GET.get("order_by", "default")

    # Применение фильтрации по количеству комнат
    if rooms:
        apartments = apartments.filter(rooms=rooms)

    # Применение фильтрации по размеру квартиры
    if min_size:
        apartments = apartments.filter(apartment_size__gte=min_size)
    if max_size:
        apartments = apartments.filter(apartment_size__lte=max_size)

    # Сортировка по цене
    if order_by == "price":
        apartments = apartments.order_by("price")
    elif order_by == "-price":
        apartments = apartments.order_by("-price")

    # Фильтрация по сегодняшней дате
    today = timezone.now().date()
    apartments_today = apartments.filter(date=today)

    # Если нет данных за сегодня, фильтруем по вчерашней дате
    if not apartments_today.exists():
        yesterday = today - timedelta(days=1)
        apartments = apartments.filter(date=yesterday)
    else:
        apartments = apartments_today

    # Пагинация
    page = request.GET.get("page", 1)
    if page == "Next":
        page = 1
    else:
        page = int(page)
    apartments = apartments[(page - 1) * 9 : page * 9]

    # Подготовка параметров для передачи в шаблон
    current_page = int(request.GET.get("page", 1))
    next_page = current_page + 1

    # Составление параметров фильтров для сохранения при переходе между страницами
    filter_params = {
        "rooms": rooms,
        "min_size": min_size,
        "max_size": max_size,
        "order_by": order_by,
    }

    # Отправка данных в шаблон
    return render(
        request,
        "goods/catalog.html",
        {
            "apartments": apartments,
            "next_page": next_page,
            "page": page,
            "filter_params": filter_params,
        },
    )

goods/templates/goods/catalog.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
<div class="row">
    <!-- Форма фильтров -->
    <div class="dropdown mb-2">
        <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            Фильтры
        </button>

        <form action="" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="checkbox" name="on_sale" id="onSale" value="on" {% if request.GET.on_sale %}checked{% endif %}>
                <label class="form-check-label" for="onSale">
                    Только доступные квартиры
                </label>
            </div>

            <p class="text-white mx-3 mt-3">Сортировать по:</p>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="default" value="default" checked {% if request.GET.order_by == 'default' %}checked{% endif %}>
                <label class="form-check-label" for="default">
                    По умолчанию
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="price" value="price" {% if request.GET.order_by == 'price' %}checked{% endif %}>
                <label class="form-check-label" for="price">
                    От дешевых к дорогим
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="price_desc" value="-price" {% if request.GET.order_by == '-price' %}checked{% endif %}>
                <label class="form-check-label" for="price_desc">
                    От дорогих к дешевым
                </label>
            </div>

            <p class="text-white mx-3 mt-3">Размер квартиры (м²):</p>
            <input type="number" class="form-control mx-3" name="min_size" placeholder="Минимальный размер" min="0" value="{{ request.GET.min_size }}">
            <input type="number" class="form-control mx-3" name="max_size" placeholder="Максимальный размер" min="0" value="{{ request.GET.max_size }}">

            <p class="text-white mx-3 mt-3">Количество комнат:</p>
            <select class="form-select mx-3" name="rooms">
                <option value="">Все</option>
                <option value="1" {% if request.GET.rooms == '1' %}selected{% endif %}>1</option>
                <option value="2" {% if request.GET.rooms == '2' %}selected{% endif %}>2</option>
                <option value="3" {% if request.GET.rooms == '3' %}selected{% endif %}>3</option>
                <option value="4" {% if request.GET.rooms == '4' %}selected{% endif %}>4</option>
                <option value="5" {% if request.GET.rooms == '5' %}selected{% endif %}>5+</option>
            </select>

            <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
        </form>
    </div>

    {% for apartment in apartments %}
    <div class="col-12 p-4">
        <div class="card border-primary rounded custom-shadow">
            <div class="card-body">
                <a href="{{ apartment.link }}">
                    <p class="card-title">{{ apartment.place }}</p>
                </a>
                <div class="d-flex justify-content-between">
                    <p class="card-text text-truncate">
                        {{ apartment.rooms }} комнаты, {{ apartment.apartment_size }} м², Этаж: {{ apartment.floor }}
                    </p>
                    <!-- Контейнер для цены и кнопки "Анализ" -->
                    <div class="d-flex align-items-center">
                        <p><strong>{{ apartment.price }} $</strong></p>
                        <a href="{% url 'analysis:index' apartment.flat_id %}" class="btn btn-secondary ml-2">Анализ</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<!-- Пагинация -->
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center my-4">
        {% if page != 1 %}
        <li class="page-item">
            <a class="page-link" href="?page=1{% if request.GET.rooms %}&rooms={{ request.GET.rooms }}{% endif %}{% if request.GET.min_size %}&min_size={{ request.GET.min_size }}{% endif %}{% if request.GET.max_size %}&max_size={{ request.GET.max_size }}{% endif %}{% if request.GET.order_by %}&order_by={{ request.GET.order_by }}{% endif %}">1</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page|add:-1 }}{% if request.GET.rooms %}&rooms={{ request.GET.rooms }}{% endif %}{% if request.GET.min_size %}&min_size={{ request.GET.min_size }}{% endif %}{% if request.GET.max_size %}&max_size={{ request.GET.max_size }}{% endif %}{% if request.GET.order_by %}&order_by={{ request.GET.order_by }}{% endif %}">{{ page|add:-1 }}</a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page }}{% if request.GET.rooms %}&rooms={{ request.GET.rooms }}{% endif %}{% if request.GET.min_size %}&min_size={{ request.GET.min_size }}{% endif %}{% if request.GET.max_size %}&max_size={{ request.GET.max_size }}{% endif %}{% if request.GET.order_by %}&order_by={{ request.GET.order_by }}{% endif %}">{{ page }} </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page|add:1 }}{% if request.GET.rooms %}&rooms={{ request.GET.rooms }}{% endif %}{% if request.GET.min_size %}&min_size={{ request.GET.min_size }}{% endif %}{% if request.GET.max_size %}&max_size={{ request.GET.max_size }}{% endif %}{% if request.GET.order_by %}&order_by={{ request.GET.order_by }}{% endif %}">{{ page|add:1 }}</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ next_page }}{% if request.GET.rooms %}&rooms={{ request.GET.rooms }}{% endif %}{% if request.GET.min_size %}&min_size={{ request.GET.min_size }}{% endif %}{% if request.GET.max_size %}&max_size={{ request.GET.max_size }}{% endif %}{% if request.GET.order_by %}&order_by={{ request.GET.order_by }}{% endif %}">Далее</a>
        </li>
    </ul>
</nav>

{% endblock %}

{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Home Python Hub Studio 2023</p>
    </div>
</footer>
{% endblock footer %}